mendersoftware/create-artifact-worker

README.md

changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>

standard README

---

LIC_FILES_CHKSUM.sha256
client/deployments.go
client/s3.go
cmd/single-file.go
config/config.go
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/Makefile
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/appveyor.yml
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/go113.go
vendor/github.com/pkg/errors/stack.go
vendor/vendor.json

next up will the implementation of the command itself.
then I'll se if any unit tests make sense and add some.

create-artifact cli part 2: clients for external services

---

client/deployments.go
client/s3.go
cmd/single-file.go
config/config.go
log/log.go

hopefully the last one of:
https://tracker.mender.io/browse/MEN-3039
@oleorhagen FYI for your pr.

single-file module artifact generation command implementation

---

client/deployments.go

Changelog: none
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>

Add "default" tenant support in internal artifact upload end-point

---

.gitlab-ci.yml

Depends on https://github.com/mendersoftware/mendertesting/pull/43

QA-129: Adapt CI pipeline following upstream changes in pipelines

---

.gitlab-ci.yml

QA-129: Adapt CI pipeline following upstream changes in pipelines - 1.0.x

---

LIC_FILES_CHKSUM.sha256
license_test.go

Add missing license in LIC_FILES_CHKSUM.sha256

---

client/deployments.go

MEN-3539: increase download and upload time-outs to 15 minutes

---

cmd/single-file.go

MEN-3771: Handle multiple device types

---

Dockerfile
config.yaml
workflows/generate_artifact.json

Rebuild to upgrade to the latest back-incompatible workflows client

---

.gitlab-ci.yml
Dockerfile

1.0.x: Dockerfile: lock base image mendersoftware/workflows to mender-3.1.x

---

.gitlab-ci.yml
client/deployments.go
client/s3.go
cmd/single-file.go

QA-235: pipeline: Switch to static checks by golangci-lint

---

Dockerfile
LICENSE
LIC_FILES_CHKSUM.sha256

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

Bump mender-artifact to version 3.6.1

---

Dockerfile
LICENSE
LIC_FILES_CHKSUM.sha256

chore(security): fix CVEs rebuilding using the latest `workflows:master`

---

Dockerfile

Changelog: Title
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

Switch to stable components in create-artifact-worker 1.1.x.

---

Dockerfile

Changelog: None
Ticket: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

fix: bump mender-artifact to 3.7.1

---

cmd/single-file.go

Ticket: [MEN-6046](https://tracker.mender.io/browse/MEN-6046)

feat: accept more single-file-artifact-gen arguments

---

Dockerfile

fix: Add missing dependency after `mender-artifact` upgrade

---

Dockerfile

Changelog: Title
Ticket: None
(cherry picked from commit 14cb1abf9cf3777b41fb9ef6cbad0e756934fbab)

feat: update mender-artifact to `3.10.1`

---

.gitlab-ci.yml
Dockerfile

Add multiplatform build

---

.github/dependabot.yml

Ticket: QA-643
Changelog: None

Keep alpine 3.18

---

.gitlab-ci.yml

Triggers mender helm version bump to
values-staging.yaml and values-prod.yaml in the mender-helm repository
Ticket: MC-6856

Hosted Mender rolling release

---

Dockerfile

https://tip.golang.org/doc/devel/release#go1.22.minor

Bump golang to go1.22.2
